import '../../core/logging/app_logger.dart';
import '../pipeline/edit_operation.dart';
import '../pipeline/edit_pipeline.dart';
import 'preset.dart';

final _log = AppLogger('PresetApplier');

/// Merges a [Preset]'s operations into an [EditPipeline].
///
/// Strategy: for each op in the preset, if an op of the same TYPE already
/// exists in the pipeline, REPLACE its parameters; otherwise APPEND a
/// fresh op. This matches Lightroom's preset semantics where applying a
/// preset leaves unaffected panels untouched.
///
/// Applying the 'Original' preset (empty operations) is a no-op.
class PresetApplier {
  const PresetApplier();

  EditPipeline apply(Preset preset, EditPipeline base) {
    _log.i('apply', {
      'preset': preset.name,
      'opsInPreset': preset.operations.length,
      'opsInBase': base.operations.length,
    });
    var next = base;
    for (final presetOp in preset.operations) {
      final existing = next.operations.where((o) => o.type == presetOp.type);
      if (existing.isNotEmpty) {
        // Replace in place with the preset's parameter values. We keep
        // the existing op id (so slider thumbs follow the change via
        // the id cache) AND the existing enabled flag (so applying a
        // preset doesn't un-disable ops the user intentionally turned
        // off). Only honour the preset's `enabled` flag if the preset
        // author explicitly provided one — freezed's default is true,
        // so we compare against the presetOp's own field.
        final replaced = existing.first.copyWith(
          parameters: Map.of(presetOp.parameters),
        );
        next = next.replace(replaced);
      } else {
        // Append a fresh op with a new id generated by EditOperation.create.
        next = next.append(
          EditOperation.create(
            type: presetOp.type,
            parameters: Map.of(presetOp.parameters),
          ),
        );
      }
    }
    return next;
  }
}
