/// XVI.96 (B2) — In-memory representation of a single test-corpus
/// image.
///
/// Mirrors one entry in `assets/test_images/manifest.json`. The
/// corpus is generated by `scripts/generate_test_corpus.py`; the
/// loader in [TestCorpus] parses the manifest into instances of
/// this class.
library;

import 'package:flutter/foundation.dart';

/// A single image in the test corpus.
@immutable
class TestImage {
  const TestImage({
    required this.id,
    required this.path,
    required this.width,
    required this.height,
    required this.category,
    required this.groundTruth,
    required this.expectedOps,
    this.notes,
  });

  /// Stable identifier used in commit-message trailers and the lab
  /// UI (`"portrait_silhouette"`).
  final String id;

  /// Asset-relative path of the source image (`"assets/test_images/
  /// portrait_silhouette.png"`).
  final String path;

  /// Pre-decoded dimensions, for layout without paying the decode
  /// cost. The lab cross-checks this against the decoded image.
  final int width;
  final int height;

  /// Category tag used to filter the lab carousel by intent
  /// (`"portrait"`, `"landscape"`, `"reference_clean"`, …).
  final String category;

  /// Optional ground-truth asset paths keyed by kind:
  /// `"alpha"`, `"sky_mask"`, `"clean_reference"`, `"noisy_variant"`,
  /// `"sharp_reference"`, `"blurred_variant"`, `"object_mask"`,
  /// `"tap_points"` (latter is `List<Map<String, dynamic>>`).
  final Map<String, Object> groundTruth;

  /// AI op IDs this image is designed to validate. Used by the lab
  /// to highlight the right ops in the picker and by the matrix
  /// runner to decide which (op, image) pairs to score.
  final List<String> expectedOps;

  /// Free-form per-image note carried from the manifest.
  final String? notes;

  /// Parse a single entry from the manifest JSON.
  factory TestImage.fromManifest(Map<String, Object?> json) {
    Object? gt = json['groundTruth'];
    Map<String, Object> groundTruth = const {};
    if (gt is Map) {
      groundTruth = gt.map(
        (k, v) => MapEntry(k.toString(), v as Object),
      );
    }
    final ops = json['expectedOps'];
    if (ops is! List) {
      throw FormatException(
        'TestImage.fromManifest: "expectedOps" must be a list, got $ops',
      );
    }
    return TestImage(
      id: json['id'] as String,
      path: json['path'] as String,
      width: json['width'] as int,
      height: json['height'] as int,
      category: json['category'] as String,
      groundTruth: groundTruth,
      expectedOps: ops.map((e) => e.toString()).toList(growable: false),
      notes: json['notes'] as String?,
    );
  }

  /// Convenience getter for the alpha-matte ground truth path, if
  /// the image declares one. Returns `null` when the corresponding
  /// op is behavioural-only.
  String? get alphaPath => groundTruth['alpha'] as String?;

  /// Convenience getter for the sky-mask ground truth path.
  String? get skyMaskPath => groundTruth['sky_mask'] as String?;

  /// Convenience getter for the object-mask ground truth (inpaint).
  String? get objectMaskPath => groundTruth['object_mask'] as String?;

  /// Convenience getter for the clean-reference path on noisy
  /// images. Used by PSNR-vs-reference grading.
  String? get cleanReferencePath =>
      groundTruth['clean_reference'] as String?;

  /// Convenience getter for the noisy variant of a clean image.
  String? get noisyVariantPath => groundTruth['noisy_variant'] as String?;

  /// Convenience getter for the sharp reference of a blurred image.
  String? get sharpReferencePath =>
      groundTruth['sharp_reference'] as String?;

  /// Convenience getter for the blurred variant of a sharp image.
  String? get blurredVariantPath =>
      groundTruth['blurred_variant'] as String?;

  /// Convenience getter for MobileSAM tap points
  /// (`[{label, x, y}, ...]`).
  List<Map<String, Object?>>? get tapPoints {
    final raw = groundTruth['tap_points'];
    if (raw is! List) return null;
    return raw
        .whereType<Map>()
        .map((m) => m.map((k, v) => MapEntry(k.toString(), v as Object?)))
        .toList(growable: false);
  }
}
