// tool/bake_luts.dart
//
// Generates the bundled 3D LUT PNG assets the [Lut3dShader] expects.
//
// The shader (`shaders/lut3d.frag`) samples a `tileSize × tileSize`
// 3D LUT laid out as a horizontal strip of `tileSize` square tiles
// — i.e. `tileSize² × tileSize` pixels. With `tileSize = 33` that's
// a 1089 × 33 RGB image where pixel (i + slice * tileSize, j) holds
// the LUT entry at (r=i/32, g=j/32, b=slice/32).
//
// To bake the bundled set:
//
//     dart run tool/bake_luts.dart
//
// Each generated PNG is written to `assets/luts/`. The companion
// `manifest.json` is regenerated with one entry per baked LUT.
//
// Adding a new film/look:
//   1. Add a `Lut(name, fn)` to the `_bakeList` below where `fn` is a
//      pure-Dart per-pixel transform from neutral RGB (each in [0,1])
//      to the desired graded RGB.
//   2. Re-run the script. The PNG + manifest entry land automatically.
//   3. The LUT shows up in the preset strip on the next app launch
//      because [BuiltInPresets] reads `manifest.json` at startup.
//
// For real `.cube` LUT files (Adobe / RNI / DaVinci exports), drop
// them in `assets/luts/source/*.cube` and extend `_loadCubeFile`
// (TODO at the bottom of this file) — the bake loop already handles
// arbitrary tile sizes.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

/// The size of one side of the cubic LUT. The shader assumes 33.
const int kTileSize = 33;

/// The output path for every baked LUT, relative to the repo root.
const String kAssetsDir = 'assets/luts';

typedef LutTransform = List<double> Function(double r, double g, double b);

class Lut {
  const Lut({
    required this.id,
    required this.name,
    required this.category,
    required this.transform,
  });
  final String id;
  final String name;
  final String category;
  final LutTransform transform;
}

/// The bundled LUT set. Each transform takes a neutral RGB triple in
/// [0, 1] and returns the graded triple. Conservative ranges so the
/// looks read as "tasteful" rather than "overcooked" — users who want
/// stronger looks can stack contrast/saturation on top.
final List<Lut> _bakeList = <Lut>[
  Lut(
    id: 'identity_33',
    name: 'Identity (debug)',
    category: 'debug',
    transform: (r, g, b) => [r, g, b],
  ),
  Lut(
    id: 'mono_33',
    name: 'Mono',
    category: 'bw',
    transform: (r, g, b) {
      // Rec.709 luma weights — same as MatrixComposer.saturation.
      final y = 0.2126 * r + 0.7152 * g + 0.0722 * b;
      return [y, y, y];
    },
  ),
  Lut(
    id: 'sepia_33',
    name: 'Sepia',
    category: 'bw',
    transform: (r, g, b) {
      final y = 0.2126 * r + 0.7152 * g + 0.0722 * b;
      // Warm split-tone on the luminance.
      return [
        (y * 1.07).clamp(0.0, 1.0),
        (y * 0.93).clamp(0.0, 1.0),
        (y * 0.74).clamp(0.0, 1.0),
      ];
    },
  ),
  Lut(
    id: 'cool_33',
    name: 'Cool',
    category: 'tone',
    transform: (r, g, b) {
      // Subtle blue-cast in shadows, neutral midtones, slight cyan
      // in highlights. Operates on a per-channel pull curve.
      double bend(double v, double low, double high) {
        // Smoothstep-shaped pull: lift low end, compress high end.
        return v + low * (1.0 - v) * v + high * (v - 0.5);
      }

      return [
        bend(r, -0.04, 0.0).clamp(0.0, 1.0),
        bend(g, 0.02, 0.02).clamp(0.0, 1.0),
        bend(b, 0.08, 0.04).clamp(0.0, 1.0),
      ];
    },
  ),
  Lut(
    id: 'warm_33',
    name: 'Warm',
    category: 'tone',
    transform: (r, g, b) {
      double bend(double v, double low, double high) {
        return v + low * (1.0 - v) * v + high * (v - 0.5);
      }

      return [
        bend(r, 0.08, 0.04).clamp(0.0, 1.0),
        bend(g, 0.02, 0.02).clamp(0.0, 1.0),
        bend(b, -0.05, -0.02).clamp(0.0, 1.0),
      ];
    },
  ),
];

void main(List<String> args) {
  final outDir = Directory(kAssetsDir);
  if (!outDir.existsSync()) {
    stderr.writeln('error: $kAssetsDir does not exist '
        '(run from the repo root)');
    exit(2);
  }

  final manifest = <Map<String, Object?>>[];
  for (final lut in _bakeList) {
    final png = _bakeOne(lut);
    final path = '$kAssetsDir/${lut.id}.png';
    File(path).writeAsBytesSync(png);
    stdout.writeln('baked $path  (${png.length} bytes)');
    manifest.add({
      'id': lut.id,
      'name': lut.name,
      'category': lut.category,
      'assetPath': path,
      'thumbnailPath': null,
    });
  }

  final manifestJson = const JsonEncoder.withIndent('  ').convert({
    r'$comment': '3D LUT manifest. Each LUT is a tileSize^3 tiled PNG '
        'applied via lut3d.frag. Generated by tool/bake_luts.dart — '
        'do not hand-edit; re-run the script after adding a new LUT.',
    'version': 1,
    'tileLayout': {
      'size': kTileSize,
      'width': kTileSize * kTileSize,
      'height': kTileSize,
    },
    'luts': manifest,
  });
  File('$kAssetsDir/manifest.json').writeAsStringSync('$manifestJson\n');
  stdout.writeln('wrote $kAssetsDir/manifest.json '
      '(${manifest.length} entries)');
}

/// Bake one LUT into a horizontally-tiled RGB PNG of size
/// `(tileSize² × tileSize)`. Pixel (i + slice * tileSize, j) holds
/// the transform of (i/(N-1), j/(N-1), slice/(N-1)).
Uint8List _bakeOne(Lut lut) {
  const n = kTileSize;
  const width = n * n;
  const height = n;
  final pixels = Uint8List(width * height * 4); // RGBA
  for (int slice = 0; slice < n; slice++) {
    final bz = slice / (n - 1);
    for (int j = 0; j < n; j++) {
      final by = j / (n - 1);
      for (int i = 0; i < n; i++) {
        final bx = i / (n - 1);
        final out = lut.transform(bx, by, bz);
        final px = (i + slice * n + j * width) * 4;
        pixels[px + 0] = (out[0] * 255).round().clamp(0, 255);
        pixels[px + 1] = (out[1] * 255).round().clamp(0, 255);
        pixels[px + 2] = (out[2] * 255).round().clamp(0, 255);
        pixels[px + 3] = 255;
      }
    }
  }
  return _encodePng(pixels, width, height);
}

// ---------------------------------------------------------------------------
// Minimal PNG encoder — IHDR + IDAT (uncompressed-DEFLATE) + IEND.
// We only need 8-bit RGBA, no interlace. Keeps the script zero-dep so
// it can be run from `dart run` without `pubspec` modifications. The
// encoder is deliberately small (~80 lines) and unit-test-able.

Uint8List _encodePng(Uint8List rgba, int width, int height) {
  final buf = BytesBuilder();
  // PNG signature.
  buf.add(const [137, 80, 78, 71, 13, 10, 26, 10]);
  // IHDR.
  final ihdr = BytesBuilder()
    ..add(_u32(width))
    ..add(_u32(height))
    ..addByte(8) // bit depth
    ..addByte(6) // color type RGBA
    ..addByte(0) // compression
    ..addByte(0) // filter
    ..addByte(0); // interlace
  _writeChunk(buf, 'IHDR', ihdr.toBytes());
  // IDAT — filter byte 0 per scanline + raw RGBA, wrapped in an
  // uncompressed zlib stream so we don't pull in a deflate impl.
  final filtered = BytesBuilder();
  final stride = width * 4;
  for (int y = 0; y < height; y++) {
    filtered.addByte(0); // filter: none
    filtered.add(rgba.sublist(y * stride, (y + 1) * stride));
  }
  final idat = _zlibStore(filtered.toBytes());
  _writeChunk(buf, 'IDAT', idat);
  _writeChunk(buf, 'IEND', Uint8List(0));
  return buf.toBytes();
}

Uint8List _u32(int v) {
  final b = ByteData(4)..setUint32(0, v);
  return b.buffer.asUint8List();
}

void _writeChunk(BytesBuilder out, String tag, Uint8List payload) {
  out.add(_u32(payload.length));
  final tagBytes = Uint8List.fromList(tag.codeUnits);
  out.add(tagBytes);
  out.add(payload);
  // CRC32 of (tag || payload).
  final crcInput = BytesBuilder()
    ..add(tagBytes)
    ..add(payload);
  out.add(_u32(_crc32(crcInput.toBytes())));
}

/// Wrap [raw] in an uncompressed zlib stream. Format: 0x78 0x01,
/// repeated `[BFINAL=last? 0x01 : 0x00, LEN_lo, LEN_hi, ~LEN_lo,
/// ~LEN_hi, raw...]` blocks (max 65535 each), Adler-32 trailer.
Uint8List _zlibStore(Uint8List raw) {
  final out = BytesBuilder();
  out.addByte(0x78); // CM=8, CINFO=7 (32K window)
  out.addByte(0x01); // no preset dict, fcheck so header % 31 == 0
  const max = 65535;
  for (int i = 0; i < raw.length; i += max) {
    final chunk = raw.sublist(i, math.min(i + max, raw.length));
    final isLast = i + chunk.length >= raw.length;
    out.addByte(isLast ? 0x01 : 0x00);
    out.addByte(chunk.length & 0xff);
    out.addByte((chunk.length >> 8) & 0xff);
    out.addByte((~chunk.length) & 0xff);
    out.addByte(((~chunk.length) >> 8) & 0xff);
    out.add(chunk);
  }
  out.add(_u32(_adler32(raw)));
  return out.toBytes();
}

int _adler32(Uint8List data) {
  int a = 1;
  int b = 0;
  for (final byte in data) {
    a = (a + byte) % 65521;
    b = (b + a) % 65521;
  }
  return ((b << 16) | a) & 0xffffffff;
}

final List<int> _crcTable = () {
  final table = List<int>.filled(256, 0);
  for (int i = 0; i < 256; i++) {
    int c = i;
    for (int k = 0; k < 8; k++) {
      c = (c & 1) != 0 ? 0xedb88320 ^ (c >> 1) : (c >> 1);
    }
    table[i] = c;
  }
  return table;
}();

int _crc32(Uint8List data) {
  int c = 0xffffffff;
  for (final byte in data) {
    c = _crcTable[(c ^ byte) & 0xff] ^ (c >> 8);
  }
  return (c ^ 0xffffffff) & 0xffffffff;
}

// TODO: support real .cube LUT files. The format is plain text:
//
//   TITLE "..."
//   LUT_3D_SIZE 33
//   r g b   (one per line, B varies fastest)
//
// Loader sketch:
//   final lines = File(path).readAsLinesSync();
//   final size = ...;
//   final entries = lines.where((l) => l.trim().split(' ').length == 3)
//       .map((l) => l.trim().split(' ').map(double.parse).toList())
//       .toList();
//   transform = (r, g, b) {
//     final ri = (r * (size - 1)).round();
//     final gi = (g * (size - 1)).round();
//     final bi = (b * (size - 1)).round();
//     final idx = bi * size * size + gi * size + ri;
//     return entries[idx];
//   };
